### ISSUE TITLE
Zombies if you chain action sheets together

### ISSUE THREAD

**Issue by mohpor** [Friend-LGA/LGActionSheet#2]
Hi,
If you try to chain action sheets by opening new action sheets inside action's blocks, it'll lead to windows being zombie out.

I think the solution would be to call blocks after dismissing and removing windows.

Any other solutions?
Thanks

**Comment by Friend-LGA** [comment]
Show me your code please.

**Comment by Friend-LGA** [comment]
Ok, I will fix it in few days. Now I am working on a big update.

**Comment by mohpor** [comment]
Great, thanks

**Comment by Friend-LGA** [comment]
Done, I fixed it. Use now [LGAlertView](https://github.com/Friend-LGA/LGAlertView).
